package com.bccommittee.adapter;

import android.content.Context;
import android.content.Intent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.bccommittee.R;
import com.bccommittee.model.MonthlyReport;
import com.bccommittee.util.CurrencyUtil;

import java.util.ArrayList;
import java.util.List;

public class ReportAdapter extends RecyclerView.Adapter<ReportAdapter.ReportViewHolder> {

    private final Context context;
    private List<MonthlyReport> reports = new ArrayList<>();
    private int expandedPos = 0; // first item expanded by default

    public ReportAdapter(Context context) {
        this.context = context;
    }

    public void setReports(List<MonthlyReport> reports) {
        this.reports = new ArrayList<>(reports);
        notifyDataSetChanged();
    }

    @NonNull
    @Override
    public ReportViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View v = LayoutInflater.from(context).inflate(R.layout.item_report, parent, false);
        return new ReportViewHolder(v);
    }

    @Override
    public void onBindViewHolder(@NonNull ReportViewHolder holder, int position) {
        MonthlyReport r = reports.get(position);
        holder.bind(r, position, expandedPos == position);

        holder.layoutHeader.setOnClickListener(v -> {
            int prev = expandedPos;
            expandedPos = (expandedPos == position) ? -1 : position;
            notifyItemChanged(prev);
            notifyItemChanged(position);
        });

        holder.btnExport.setOnClickListener(v -> {
            String shareText = buildShareText(r);
            Intent intent = new Intent(Intent.ACTION_SEND);
            intent.setType("text/plain");
            intent.putExtra(Intent.EXTRA_TEXT, shareText);
            context.startActivity(Intent.createChooser(intent, "Share Report"));
        });
    }

    @Override
    public int getItemCount() { return reports.size(); }

    private String buildShareText(MonthlyReport r) {
        return "BC Committee — " + r.getMonth() + " Report\n" +
               "──────────────────\n" +
               "Monthly Collection : " + CurrencyUtil.format(r.getCollected()) + "\n" +
               "Interest Received  : " + CurrencyUtil.format(r.getInterestIn()) + "\n" +
               "Member Fees        : " + CurrencyUtil.format(r.getFees()) + "\n" +
               "Penalties          : " + CurrencyUtil.format(r.getPenalties()) + "\n" +
               "Defaults           : " + r.getDefaults() + " member(s)\n" +
               "Total Revenue      : " + CurrencyUtil.format(r.getTotalRevenue()) + "\n" +
               "Fund Pool          : " + CurrencyUtil.format(r.getTotalFund()) + "\n" +
               "──────────────────\n" +
               "Generated by BC Committee App";
    }

    class ReportViewHolder extends RecyclerView.ViewHolder {
        LinearLayout layoutHeader, layoutDetails, layoutReportRows;
        TextView tvMonth, tvPool, tvCurrentBadge, tvDefaultBadge, tvChevron;
        Button btnExport;

        ReportViewHolder(View v) {
            super(v);
            layoutHeader     = v.findViewById(R.id.layout_header);
            layoutDetails    = v.findViewById(R.id.layout_details);
            layoutReportRows = v.findViewById(R.id.layout_report_rows);
            tvMonth          = v.findViewById(R.id.tv_month);
            tvPool           = v.findViewById(R.id.tv_pool);
            tvCurrentBadge   = v.findViewById(R.id.tv_current_badge);
            tvDefaultBadge   = v.findViewById(R.id.tv_default_badge);
            tvChevron        = v.findViewById(R.id.tv_chevron);
            btnExport        = v.findViewById(R.id.btn_export);
        }

        void bind(MonthlyReport r, int pos, boolean expanded) {
            tvMonth.setText(r.getMonth());
            tvPool.setText("Pool: " + CurrencyUtil.format(r.getTotalFund()));

            tvCurrentBadge.setVisibility(pos == 0 ? View.VISIBLE : View.GONE);
            tvDefaultBadge.setVisibility(r.getDefaults() > 0 ? View.VISIBLE : View.GONE);
            tvChevron.setText(expanded ? "▲" : "▼");
            layoutDetails.setVisibility(expanded ? View.VISIBLE : View.GONE);

            if (expanded) {
                layoutReportRows.removeAllViews();
                addRow("Monthly Collection", CurrencyUtil.format(r.getCollected()),
                       R.color.color_green);
                addRow("Interest Received",  CurrencyUtil.format(r.getInterestIn()),
                       R.color.color_blue);
                addRow("Member Fees",        CurrencyUtil.format(r.getFees()),
                       R.color.color_orange);
                addRow("Penalties",          CurrencyUtil.format(r.getPenalties()),
                       r.getPenalties() > 0 ? R.color.color_red : R.color.text_muted);
                addRow("Defaults",           r.getDefaults() + " member(s)",
                       r.getDefaults() > 0 ? R.color.color_red : R.color.color_green);
                addRow("Total Revenue",      CurrencyUtil.format(r.getTotalRevenue()),
                       R.color.text_primary);
            }
        }

        private void addRow(String label, String value, int colorRes) {
            View row = LayoutInflater.from(context)
                .inflate(android.R.layout.simple_list_item_2, layoutReportRows, false);

            LinearLayout rowLayout = new LinearLayout(context);
            rowLayout.setOrientation(LinearLayout.HORIZONTAL);
            LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT);
            rowLayout.setLayoutParams(lp);
            rowLayout.setPadding(0, dp(8), 0, dp(8));

            // Divider
            View divider = new View(context);
            LinearLayout.LayoutParams dividerLp = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT, dp(1));
            divider.setLayoutParams(dividerLp);
            divider.setBackgroundColor(context.getColor(R.color.divider_color));

            TextView tvLabel = new TextView(context);
            tvLabel.setLayoutParams(new LinearLayout.LayoutParams(0,
                LinearLayout.LayoutParams.WRAP_CONTENT, 1));
            tvLabel.setText(label);
            tvLabel.setTextColor(context.getColor(R.color.text_muted));
            tvLabel.setTextSize(12);

            TextView tvValue = new TextView(context);
            tvValue.setText(value);
            tvValue.setTextColor(context.getColor(colorRes));
            tvValue.setTextSize(13);
            tvValue.setTypeface(null, android.graphics.Typeface.BOLD);

            rowLayout.addView(tvLabel);
            rowLayout.addView(tvValue);
            layoutReportRows.addView(divider);
            layoutReportRows.addView(rowLayout);
        }

        private int dp(int v) {
            return (int) (v * context.getResources().getDisplayMetrics().density);
        }
    }
}
